create database CarritoCompra;

GRANT ALL PRIVILEGES ON CarritoCompra.* TO 'gomez'@'%' identified by 'javi';

create table CarritoCompra.USUARIO (
	nickname VARCHAR(50) PRIMARY KEY,
	nombre VARCHAR(50),
	apellidos VARCHAR(50),
	email VARCHAR(50),
	contrasena VARCHAR(50),
	fecha_nac DATE,
	genero VARCHAR(50),
	es_admin VARCHAR(50)
);

CREATE TABLE CarritoCompra.CATEGORIA(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(40),
	descripcion VARCHAR(500)
);


create table CarritoCompra.ARTICLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50),
	description TEXT,
	price DECIMAL(5,2),
	id_categoria INT,
	CONSTRAINT FK_ARTICLES FOREIGN KEY (id_categoria) REFERENCES CarritoCompra.CATEGORIA(id) ON DELETE CASCADE
);

CREATE TABLE CarritoCompra.USUARIO_ARTICLES(
	name_usuario VARCHAR(50),
	id_article INT,
	CONSTRAINT PK PRIMARY KEY (name_usuario,id_article),
	CONSTRAINT FK1 FOREIGN KEY (id_article) REFERENCES ARTICLES(id) ON DELETE CASCADE,
	CONSTRAINT FK2 FOREIGN KEY (name_usuario) REFERENCES USUARIO(nickname) ON DELETE CASCADE
);

insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('FRUTA', 'nam ultrices');
insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('VERDURA', 'nam ultrices');
insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('PESCADO', 'nam ultrices');
insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('NOSE', 'nam ultrices');

insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (1, 'Potatoes - Idaho 80 Count', 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit', 93.02, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (2, 'Beef - Ox Tongue', 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', 54.22, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (3, 'Bread Base - Goodhearth', 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 8.78, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (4, 'Bread - Crusty Italian Poly', 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 35.64, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (5, 'Campari', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 48.39, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (6, 'Foil Cont Round', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue', 74.55, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (7, 'Basil - Primerba, Paste', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 71.73, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (8, 'Eggplant - Regular', 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 50.75, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (9, 'Calypso - Pineapple Passion', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', 93.31, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (10, 'Soup - French Can Pea', 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', 17.57, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (11, 'Lettuce - Sea / Sea Asparagus', 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum', 77.02, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (12, 'Swiss Chard', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', 54.98, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (13, 'Dill Weed - Dry', 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce', 77.21, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (14, 'Foil Cont Round', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 17.13, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (15, 'Emulsifier', 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede', 57.46, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (16, 'Cauliflower', 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 41.24, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (17, 'Peas Snow', 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 50.53, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (18, 'Numi - Assorted Teas', 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 42.83, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (19, 'Tilapia - Fillets', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', 70.19, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (20, 'Chips - Doritos', 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', 51.47, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (21, 'Wine - Sicilia Igt Nero Avola', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', 29.04, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (22, 'Beans - Wax', 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', 78.95, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (23, 'Beef - Top Butt Aaa', 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', 55.76, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (24, 'Wine - White, Lindemans Bin 95', 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 94.55, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (25, 'Cucumber - English', 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', 96.56, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (26, 'Lentils - Green, Dry', 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 12.65, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (27, 'Bandage - Fexible 1x3', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis', 56.12, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (28, 'Wine - Penfolds Koonuga Hill', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 76.49, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (29, 'Sobe - Orange Carrot', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', 2.74, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (30, 'Strawberries - California', 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', 91.97, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (31, 'Magnotta Bel Paese Red', 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', 77.32, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (32, 'Pasta - Canelloni, Single Serve', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 89.03, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (33, 'Beef - Tenderloin - Aa', 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero', 62.09, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (34, 'Water - Spring Water, 355 Ml', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 87.61, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (35, 'Oil - Peanut', 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 89.22, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (36, 'Oil - Food, Lacquer Spray', 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas', 83.72, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (37, 'Wine - Pinot Noir Mondavi Coastal', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper', 2.37, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (38, 'Corn - Cream, Canned', 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 83.98, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (39, 'Wine - Sauvignon Blanc', 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 68.48, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (40, 'Cocktail Napkin Blue', 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 96.73, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (41, 'Mousse - Mango', 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', 67.36, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (42, 'Wine - White Cab Sauv.on', 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 37.86, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (43, 'Bread Country Roll', 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 47.73, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (44, 'Grapefruit - White', 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 77.09, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (45, 'Appetizer - Assorted Box', 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 31.47, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (46, 'Pastry - Lemon Danish - Mini', 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', 83.68, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (47, 'Muffin Chocolate Individual Wrap', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 10.35, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (48, 'Wine - Jaboulet Cotes Du Rhone', 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 78.44, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (49, 'Butter - Unsalted', 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 14.72, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, id_categoria) values (50, 'Tumeric', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', 72.36, 2);


insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('Javi', 'Javi', 'Gomez', 'javi@gmail.com', '3e5f2ce4f1d29846c7c2478679be4f3d', '2002-05-02', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('xadame0', 'Xerxes', 'Adame', 'xadame0@noaa.gov', 'abfde839bcd8f4e609b0d6eed93d64b1', '1979-03-08', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('sfedder1', 'Sonnie', 'Fedder', 'sfedder1@prnewswire.com', '815236005f54b502953912883a60ab5d', '1996-01-15', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('ccovelle2', 'Camila', 'Covelle', 'ccovelle2@seattletimes.com', '253ab4ed52a3089589bec6c804b02e28', '2013-05-07', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rminchella3', 'Rollie', 'Minchella', 'rminchella3@telegraph.co.uk', 'e1ca1a23bed59d68c479d09984f52b42', '2017-09-23', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lrasp4', 'Leroi', 'Rasp', 'lrasp4@yellowbook.com', '6000c9b6f2feed7eefbd75adf16ea788', '2001-08-22', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lmcmoyer5', 'Lyman', 'McMoyer', 'lmcmoyer5@soup.io', 'be055d05f6bbb7374e9cc15975a99699', '2001-12-29', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('tlatour6', 'Tibold', 'Latour', 'tlatour6@nba.com', 'a8049398a6c34e7d1229c6393f17e770', '2019-09-03', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('sandriulis7', 'Simon', 'Andriulis', 'sandriulis7@icq.com', '765a2805cf6262e1a3a2c81955b9dff0', '2010-12-03', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('aswetland8', 'Ancell', 'Swetland', 'aswetland8@jiathis.com', 'd2e9f672b2560c52f2970015e038c132', '1994-09-06', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('breichelt9', 'Bartolemo', 'Reichelt', 'breichelt9@wikia.com', '532e5505fd57cbe6abf2df763467b654', '1976-04-17', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dnoara', 'Dorthea', 'Noar', 'dnoara@nps.gov', 'abe86fc33752068871aa1beceeaf2791', '1997-05-03', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('ecrutb', 'Etheline', 'Crut', 'ecrutb@mediafire.com', '2d4dc117594bab6442232c9e218f581b', '1982-11-05', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rdoddemeadec', 'Reidar', 'Doddemeade', 'rdoddemeadec@icio.us', 'f65c72a29ed44cd479c501295f2a2e04', '1985-10-18', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('plandellsd', 'Patricia', 'Landells', 'plandellsd@parallels.com', '6c94cb23a3899fb3a560d8af337ef5c1', '1971-03-13', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('sharme', 'Sara', 'Harm', 'sharme@simplemachines.org', '5ba70be692b0286cc2aa5da740ccaa52', '2015-04-11', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('epartonf', 'Elfreda', 'Parton', 'epartonf@hexun.com', '24481b67984e35ae1127eee42838c915', '1999-01-23', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('ncoupmang', 'Nedda', 'Coupman', 'ncoupmang@economist.com', '9207ed7ff3917da31da8d70c268e6091', '1980-12-02', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('skamiyamah', 'Sherilyn', 'Kamiyama', 'skamiyamah@unicef.org', '013e0eef0c59b048d98d7c16ddc7d5a4', '2018-02-27', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('snewcomeni', 'Sutherland', 'Newcomen', 'snewcomeni@fda.gov', '3a523b691d44ce631cd9e1dd5fdd904b', '1971-07-09', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('hkayj', 'Hanna', 'Kay', 'hkayj@vistaprint.com', 'a6743565834f9bbb76a816f9b0e80426', '2014-06-05', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rlavallk', 'Rodrique', 'Lavall', 'rlavallk@bigcartel.com', '7ef6ab67cb86200dd5d593e044c79702', '1970-01-26', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('gprestnerl', 'Griffie', 'Prestner', 'gprestnerl@google.pl', 'eaa6aa5e62dc886307f7f89c08c033c3', '1982-06-02', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('jdenisetm', 'Janelle', 'Deniset', 'jdenisetm@is.gd', '9273d8d075c8a15d6d50451105090015', '1978-11-25', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('bwillmettn', 'Bethany', 'Willmett', 'bwillmettn@storify.com', 'a7faf49dcb17bbffdd6f6b11ed17f392', '2000-11-20', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('mattoco', 'Mathew', 'Attoc', 'mattoco@nsw.gov.au', '00bc98113f61b800b53f38baebc60e94', '2008-11-11', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('hashleyp', 'Huberto', 'Ashley', 'hashleyp@godaddy.com', 'fc6019b42b975b2b69f38d86f5dfb757', '2000-04-25', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lwilderspoonq', 'Livvyy', 'Wilderspoon', 'lwilderspoonq@bbc.co.uk', '20f47ddfc09b685a9ffaec97f6debbb7', '2000-12-30', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('kbrokr', 'Kerry', 'Brok', 'kbrokr@youku.com', 'c5c2de9f0ee41450cf5799d3b5967514', '2011-11-14', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('pcattericks', 'Patton', 'Catterick', 'pcattericks@dedecms.com', '2f9104cafefdb9a22b40933b9f1f8573', '1990-11-05', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('wleightont', 'Wright', 'Leighton', 'wleightont@tripod.com', '4d6bc5e124639a5fb9ab412bcfdabbac', '1978-01-20', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('eugolottiu', 'Euell', 'Ugolotti', 'eugolottiu@va.gov', 'f612df27d50bebaa5b693f63d59a6127', '1980-10-31', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('taddymanv', 'Tiphanie', 'Addyman', 'taddymanv@com.com', '6b04299987c545a83a18dd738c417169', '2018-07-25', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dhelliwellw', 'Dionne', 'Helliwell', 'dhelliwellw@ezineCarritoCompra.ARTICLES.com', '987d8cdf4f86ad8900b6228fdf8b4802', '1973-03-21', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('vlaurenzx', 'Valeda', 'Laurenz', 'vlaurenzx@cafepress.com', '337a018073689385391e7f244e151b57', '1976-01-24', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('cyitzovitzy', 'Cullin', 'Yitzovitz', 'cyitzovitzy@1688.com', 'f89a73eb0c250d54c0a15e381348768d', '1985-06-01', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('wchansonnauz', 'Winifield', 'Chansonnau', 'wchansonnauz@liveinternet.ru', 'b074f2b9928fef7e79ea459a419eb8dc', '2005-03-22', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('jspowage10', 'Jessie', 'Spowage', 'jspowage10@storify.com', '7ca25d9ed6fda10f63f27e976116a06f', '2008-08-01', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('nfawltey11', 'Nelia', 'Fawltey', 'nfawltey11@mtv.com', '48105552aaa511e814a2e15cfa19c72f', '1982-04-07', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dribchester12', 'Dino', 'Ribchester', 'dribchester12@sciencedaily.com', '13caa33d8251e11000a5e8336b0cb6bc', '2019-06-07', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rrothwell13', 'Reidar', 'Rothwell', 'rrothwell13@house.gov', 'b27cf4b4cea44df7c80ee1ebb3ea7ada', '2017-02-08', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('tloudiane14', 'Trueman', 'Loudiane', 'tloudiane14@hugedomains.com', '530958fca20cfd3a3d114ef111dd4b97', '2004-07-29', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dsutherington15', 'Dulci', 'Sutherington', 'dsutherington15@omniture.com', '36f4efa4b1b3145ae8d38714e51f7bf9', '2003-06-11', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('tchaff16', 'Trudi', 'Chaff', 'tchaff16@foxnews.com', '094d9a4634839a3bce1c6a90f558e5fa', '2014-11-25', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('beastlake17', 'Bobbette', 'Eastlake', 'beastlake17@newyorker.com', 'b39ccfe81f1cad8bff43b15ed2303596', '2018-06-25', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lfishleigh18', 'Laird', 'Fishleigh', 'lfishleigh18@meetup.com', 'bf14f4e82374c67d8b6c7cc7f50b8568', '2016-09-22', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('oframpton19', 'Orbadiah', 'Frampton', 'oframpton19@odnoklassniki.ru', '2dc079c67f8528f474001b2784459214', '2020-02-19', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lbleas1a', 'Liv', 'Bleas', 'lbleas1a@blinklist.com', 'dd312f60cab417f97d9d1507e912cbde', '2008-11-04', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('aclayfield1b', 'Augy', 'Clayfield', 'aclayfield1b@dell.com', 'b245a470c60520e04ce23a2af9bd9d5c', '1990-10-19', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('bgrundon1c', 'Brenden', 'Grundon', 'bgrundon1c@gov.uk', 'b153d03c6f2e1a3366aaf8aff6ae7428', '1973-02-10', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('gpierse1d', 'Gerrilee', 'Pierse', 'gpierse1d@nih.gov', 'ae2cefc539a6adbc3358ca0c0e7688f1', '1971-02-21', 'F', true);
