create database CarritoCompra;

GRANT ALL PRIVILEGES ON CarritoCompra.* TO 'gomez'@'%' identified by 'javi';

create table CarritoCompra.USUARIO (
	nickname VARCHAR(50) PRIMARY KEY,
	nombre VARCHAR(50),
	apellidos VARCHAR(50),
	email VARCHAR(50),
	contrasena VARCHAR(50),
	fecha_nac DATE,
	genero VARCHAR(50),
	es_admin VARCHAR(50)
);

CREATE TABLE CarritoCompra.CATEGORIA(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(40),
	descripcion VARCHAR(500)
);


create table CarritoCompra.ARTICLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50),
	description TEXT,
	price DECIMAL(5,2),
    stock int,
	id_categoria INT,
	CONSTRAINT FK_ARTICLES FOREIGN KEY (id_categoria) REFERENCES CarritoCompra.CATEGORIA(id) ON DELETE CASCADE
);

CREATE TABLE CarritoCompra.USUARIO_ARTICLES(
	name_usuario VARCHAR(50),
	id_article INT,
    fecha DATETIME,
    cantidad INT,
    precio DECIMAL(5,2),
	CONSTRAINT PK PRIMARY KEY (name_usuario,id_article, fecha),
	CONSTRAINT FK1 FOREIGN KEY (id_article) REFERENCES ARTICLES(id) ON DELETE CASCADE,
	CONSTRAINT FK2 FOREIGN KEY (name_usuario) REFERENCES USUARIO(nickname) ON DELETE CASCADE
);

insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('FRUTA', 'nam ultrices');
insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('VERDURA', 'nam ultrices');
insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('PESCADO', 'nam ultrices');
insert into CarritoCompra.CATEGORIA (nombre, descripcion) values ('NOSE', 'nam ultrices');

insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (1, 'Beer - Upper Canada Light', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris', 47.86, 30, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (2, 'Wine - Gato Negro Cabernet', 'ligula in lacus curabitur at ipsum ac tellus semper interdum', 91.23, 38, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (3, 'Kiwi', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 23.59, 15, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (4, 'Beer - Rickards Red', 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 12.79, 36, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (5, 'Red Currant Jelly', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 83.12, 60, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (6, 'Energy - Boo - Koo', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 18.76, 31, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (7, 'Soap - Mr.clean Floor Soap', 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', 14.45, 47, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (8, 'Bread - Focaccia Quarter', 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 8.57, 22, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (9, 'Appetizer - Escargot Puff', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', 81.33, 88, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (10, 'Radish - Pickled', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla', 25.5, 30, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (11, 'Cheese - Le Cru Du Clocher', 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in', 55.6, 59, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (12, 'Veal - Knuckle', 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus', 55.83, 48, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (13, 'Grapefruit - Pink', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 8.19, 43, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (14, 'Napkin Colour', 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 89.97, 41, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (15, 'Spaghetti Squash', 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa', 41.23, 26, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (16, 'Liners - Banana, Paper', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 87.42, 64, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (17, 'Plasticspoonblack', 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis', 50.26, 38, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (18, 'Longos - Assorted Sandwich', 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', 44.66, 57, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (19, 'Spice - Greek 1 Step', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 22.36, 51, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (20, 'Chip - Potato Dill Pickle', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 30.14, 88, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (21, 'Pork Loin Cutlets', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 94.76, 43, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (22, 'Maple Syrup', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', 51.16, 89, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (23, 'Mushroom - King Eryingii', 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', 97.42, 74, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (24, 'Juice - Orange', 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', 43.93, 49, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (25, 'Cattail Hearts', 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis', 68.54, 90, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (26, 'Chocolate - Liqueur Cups With Foil', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', 46.4, 1, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (27, 'Flower - Daisies', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 61.15, 69, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (28, 'Mushroom - Morel Frozen', 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 70.77, 6, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (29, 'Sauce - Alfredo', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit', 22.76, 98, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (30, 'Oil - Macadamia', 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', 25.51, 52, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (31, 'Basil - Primerba, Paste', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', 69.7, 26, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (32, 'Cheese - Brie, Triple Creme', 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 99.07, 89, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (33, 'Bread - Rosemary Focaccia', 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', 83.14, 90, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (34, 'Coconut - Shredded, Sweet', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 89.98, 73, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (35, 'Melon - Watermelon Yellow', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', 78.87, 98, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (36, 'Skirt - 24 Foot', 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur', 13.53, 29, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (37, 'Tomatoes - Cherry, Yellow', 'phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 63.52, 97, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (38, 'Grapefruit - Pink', 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', 63.86, 30, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (39, 'Leeks - Large', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec', 27.54, 41, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (40, 'Crab - Claws, 26 - 30', 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', 20.46, 65, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (41, 'Napkin White', 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 80.33, 72, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (42, 'Soup - Campbells, Minestrone', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 38.41, 13, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (43, 'Squash - Butternut', 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', 2.15, 69, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (44, 'Bouq All Italian - Primerba', 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 85.6, 84, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (45, 'Mousse - Banana Chocolate', 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', 25.34, 62, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (46, 'Corn - Mini', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', 3.6, 21, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (47, 'Longos - Assorted Sandwich', 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 9.92, 58, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (48, 'Rice - Brown', 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras', 18.38, 8, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (49, 'Chickensplit Half', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 62.93, 27, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (50, 'Madeira', 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at', 30.7, 49, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (51, 'Rootbeer', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 42.45, 50, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (52, 'Garlic', 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 57.73, 31, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (53, 'Artichoke - Hearts, Canned', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 49.41, 73, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (54, 'Pastry - French Mini Assorted', 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 26.29, 85, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (55, 'Water - Mineral, Natural', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', 71.97, 30, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (56, 'Food Colouring - Blue', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 2.03, 38, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (57, 'Nacho Chips', 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 97.8, 82, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (58, 'Broom - Push', 'ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 81.64, 95, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (59, 'Appetizer - Spring Roll, Veg', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', 25.57, 9, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (60, 'Onions - White', 'mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', 13.73, 47, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (61, 'Parsnip', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', 72.07, 36, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (62, 'Pork - Smoked Back Bacon', 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 57.95, 68, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (63, 'Eggplant Oriental', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 13.95, 4, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (64, 'Cheese Cloth No 60', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 13.65, 24, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (65, 'Soup Campbells Beef With Veg', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', 65.89, 33, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (66, 'Tomatoes', 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate', 18.34, 48, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (67, 'Pasta - Fettuccine, Egg, Fresh', 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', 97.15, 83, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (68, 'Capon - Breast, Wing On', 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis', 25.64, 7, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (69, 'Tomatoes - Heirloom', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 64.4, 74, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (70, 'Lettuce - Treviso', 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu', 64.68, 83, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (71, 'Lettuce - Baby Salad Greens', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 61.51, 41, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (72, 'Beans - Kidney, Red Dry', 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 27.34, 22, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (73, 'Sauce - Thousand Island', 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam', 55.4, 15, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (74, 'Teriyaki Sauce', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 78.63, 63, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (75, 'Barley - Pearl', 'morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem', 92.62, 17, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (76, 'Flour - Whole Wheat', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', 48.89, 20, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (77, 'Flour Dark Rye', 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 68.23, 60, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (78, 'Trout - Rainbow, Frozen', 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 10.15, 57, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (79, 'Shrimp - Baby, Warm Water', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis', 24.42, 42, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (80, 'Flower - Carnations', 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas', 51.21, 53, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (81, 'Sugar - Splenda Sweetener', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 51.25, 98, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (82, 'Beef - Bones, Cut - Up', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 49.53, 58, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (83, 'Syrup - Monin, Swiss Choclate', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla', 84.26, 19, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (84, 'Shortbread - Cookie Crumbs', 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', 47.23, 22, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (85, 'Catfish - Fillets', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 87.53, 3, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (86, 'Radish - Black, Winter, Organic', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 83.05, 30, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (87, 'Beef - Rouladin, Sliced', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 79.77, 33, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (88, 'Cake Circle, Foil, Scallop', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', 2.64, 34, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (89, 'Glove - Cutting', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', 67.14, 58, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (90, 'Cheese - Asiago', 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer', 29.66, 92, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (91, 'Wonton Wrappers', 'ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', 2.21, 88, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (92, 'Ostrich - Fan Fillet', 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 68.66, 95, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (93, 'Oil - Sunflower', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut', 71.54, 79, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (94, 'Cocoa Powder - Dutched', 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque', 25.0, 26, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (95, 'Nut - Walnut, Chopped', 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', 26.26, 28, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (96, 'Muffin Puck Ww Carrot', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit', 20.15, 28, 3);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (97, 'Flour - Rye', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam', 12.01, 49, 2);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (98, 'Wine - Vovray Sec Domaine Huet', 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 27.8, 51, 4);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (99, 'Goldschalger', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', 83.57, 33, 1);
insert into CarritoCompra.ARTICLES (id, name, description, price, stock, id_categoria) values (100, 'Beer - Sleeman Fine Porter', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 82.3, 41, 3);

insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('Javi', 'Javi', 'Gomez', 'javi@gmail.com', '3e5f2ce4f1d29846c7c2478679be4f3d', '2002-05-02', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('xadame0', 'Xerxes', 'Adame', 'xadame0@noaa.gov', 'abfde839bcd8f4e609b0d6eed93d64b1', '1979-03-08', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('sfedder1', 'Sonnie', 'Fedder', 'sfedder1@prnewswire.com', '815236005f54b502953912883a60ab5d', '1996-01-15', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('ccovelle2', 'Camila', 'Covelle', 'ccovelle2@seattletimes.com', '253ab4ed52a3089589bec6c804b02e28', '2013-05-07', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rminchella3', 'Rollie', 'Minchella', 'rminchella3@telegraph.co.uk', 'e1ca1a23bed59d68c479d09984f52b42', '2017-09-23', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lrasp4', 'Leroi', 'Rasp', 'lrasp4@yellowbook.com', '6000c9b6f2feed7eefbd75adf16ea788', '2001-08-22', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lmcmoyer5', 'Lyman', 'McMoyer', 'lmcmoyer5@soup.io', 'be055d05f6bbb7374e9cc15975a99699', '2001-12-29', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('tlatour6', 'Tibold', 'Latour', 'tlatour6@nba.com', 'a8049398a6c34e7d1229c6393f17e770', '2019-09-03', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('sandriulis7', 'Simon', 'Andriulis', 'sandriulis7@icq.com', '765a2805cf6262e1a3a2c81955b9dff0', '2010-12-03', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('aswetland8', 'Ancell', 'Swetland', 'aswetland8@jiathis.com', 'd2e9f672b2560c52f2970015e038c132', '1994-09-06', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('breichelt9', 'Bartolemo', 'Reichelt', 'breichelt9@wikia.com', '532e5505fd57cbe6abf2df763467b654', '1976-04-17', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dnoara', 'Dorthea', 'Noar', 'dnoara@nps.gov', 'abe86fc33752068871aa1beceeaf2791', '1997-05-03', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('ecrutb', 'Etheline', 'Crut', 'ecrutb@mediafire.com', '2d4dc117594bab6442232c9e218f581b', '1982-11-05', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rdoddemeadec', 'Reidar', 'Doddemeade', 'rdoddemeadec@icio.us', 'f65c72a29ed44cd479c501295f2a2e04', '1985-10-18', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('plandellsd', 'Patricia', 'Landells', 'plandellsd@parallels.com', '6c94cb23a3899fb3a560d8af337ef5c1', '1971-03-13', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('sharme', 'Sara', 'Harm', 'sharme@simplemachines.org', '5ba70be692b0286cc2aa5da740ccaa52', '2015-04-11', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('epartonf', 'Elfreda', 'Parton', 'epartonf@hexun.com', '24481b67984e35ae1127eee42838c915', '1999-01-23', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('ncoupmang', 'Nedda', 'Coupman', 'ncoupmang@economist.com', '9207ed7ff3917da31da8d70c268e6091', '1980-12-02', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('skamiyamah', 'Sherilyn', 'Kamiyama', 'skamiyamah@unicef.org', '013e0eef0c59b048d98d7c16ddc7d5a4', '2018-02-27', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('snewcomeni', 'Sutherland', 'Newcomen', 'snewcomeni@fda.gov', '3a523b691d44ce631cd9e1dd5fdd904b', '1971-07-09', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('hkayj', 'Hanna', 'Kay', 'hkayj@vistaprint.com', 'a6743565834f9bbb76a816f9b0e80426', '2014-06-05', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rlavallk', 'Rodrique', 'Lavall', 'rlavallk@bigcartel.com', '7ef6ab67cb86200dd5d593e044c79702', '1970-01-26', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('gprestnerl', 'Griffie', 'Prestner', 'gprestnerl@google.pl', 'eaa6aa5e62dc886307f7f89c08c033c3', '1982-06-02', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('jdenisetm', 'Janelle', 'Deniset', 'jdenisetm@is.gd', '9273d8d075c8a15d6d50451105090015', '1978-11-25', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('bwillmettn', 'Bethany', 'Willmett', 'bwillmettn@storify.com', 'a7faf49dcb17bbffdd6f6b11ed17f392', '2000-11-20', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('mattoco', 'Mathew', 'Attoc', 'mattoco@nsw.gov.au', '00bc98113f61b800b53f38baebc60e94', '2008-11-11', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('hashleyp', 'Huberto', 'Ashley', 'hashleyp@godaddy.com', 'fc6019b42b975b2b69f38d86f5dfb757', '2000-04-25', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lwilderspoonq', 'Livvyy', 'Wilderspoon', 'lwilderspoonq@bbc.co.uk', '20f47ddfc09b685a9ffaec97f6debbb7', '2000-12-30', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('kbrokr', 'Kerry', 'Brok', 'kbrokr@youku.com', 'c5c2de9f0ee41450cf5799d3b5967514', '2011-11-14', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('pcattericks', 'Patton', 'Catterick', 'pcattericks@dedecms.com', '2f9104cafefdb9a22b40933b9f1f8573', '1990-11-05', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('wleightont', 'Wright', 'Leighton', 'wleightont@tripod.com', '4d6bc5e124639a5fb9ab412bcfdabbac', '1978-01-20', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('eugolottiu', 'Euell', 'Ugolotti', 'eugolottiu@va.gov', 'f612df27d50bebaa5b693f63d59a6127', '1980-10-31', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('taddymanv', 'Tiphanie', 'Addyman', 'taddymanv@com.com', '6b04299987c545a83a18dd738c417169', '2018-07-25', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dhelliwellw', 'Dionne', 'Helliwell', 'dhelliwellw@ezineCarritoCompra.ARTICLES.com', '987d8cdf4f86ad8900b6228fdf8b4802', '1973-03-21', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('vlaurenzx', 'Valeda', 'Laurenz', 'vlaurenzx@cafepress.com', '337a018073689385391e7f244e151b57', '1976-01-24', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('cyitzovitzy', 'Cullin', 'Yitzovitz', 'cyitzovitzy@1688.com', 'f89a73eb0c250d54c0a15e381348768d', '1985-06-01', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('wchansonnauz', 'Winifield', 'Chansonnau', 'wchansonnauz@liveinternet.ru', 'b074f2b9928fef7e79ea459a419eb8dc', '2005-03-22', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('jspowage10', 'Jessie', 'Spowage', 'jspowage10@storify.com', '7ca25d9ed6fda10f63f27e976116a06f', '2008-08-01', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('nfawltey11', 'Nelia', 'Fawltey', 'nfawltey11@mtv.com', '48105552aaa511e814a2e15cfa19c72f', '1982-04-07', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dribchester12', 'Dino', 'Ribchester', 'dribchester12@sciencedaily.com', '13caa33d8251e11000a5e8336b0cb6bc', '2019-06-07', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('rrothwell13', 'Reidar', 'Rothwell', 'rrothwell13@house.gov', 'b27cf4b4cea44df7c80ee1ebb3ea7ada', '2017-02-08', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('tloudiane14', 'Trueman', 'Loudiane', 'tloudiane14@hugedomains.com', '530958fca20cfd3a3d114ef111dd4b97', '2004-07-29', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('dsutherington15', 'Dulci', 'Sutherington', 'dsutherington15@omniture.com', '36f4efa4b1b3145ae8d38714e51f7bf9', '2003-06-11', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('tchaff16', 'Trudi', 'Chaff', 'tchaff16@foxnews.com', '094d9a4634839a3bce1c6a90f558e5fa', '2014-11-25', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('beastlake17', 'Bobbette', 'Eastlake', 'beastlake17@newyorker.com', 'b39ccfe81f1cad8bff43b15ed2303596', '2018-06-25', 'F', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lfishleigh18', 'Laird', 'Fishleigh', 'lfishleigh18@meetup.com', 'bf14f4e82374c67d8b6c7cc7f50b8568', '2016-09-22', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('oframpton19', 'Orbadiah', 'Frampton', 'oframpton19@odnoklassniki.ru', '2dc079c67f8528f474001b2784459214', '2020-02-19', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('lbleas1a', 'Liv', 'Bleas', 'lbleas1a@blinklist.com', 'dd312f60cab417f97d9d1507e912cbde', '2008-11-04', 'F', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('aclayfield1b', 'Augy', 'Clayfield', 'aclayfield1b@dell.com', 'b245a470c60520e04ce23a2af9bd9d5c', '1990-10-19', 'M', false);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('bgrundon1c', 'Brenden', 'Grundon', 'bgrundon1c@gov.uk', 'b153d03c6f2e1a3366aaf8aff6ae7428', '1973-02-10', 'M', true);
insert into CarritoCompra.USUARIO (nickname, nombre, apellidos, email, contrasena, fecha_nac, genero, es_admin) values ('gpierse1d', 'Gerrilee', 'Pierse', 'gpierse1d@nih.gov', 'ae2cefc539a6adbc3358ca0c0e7688f1', '1971-02-21', 'F', true);
